# Generated by Django 5.2 on 2025-07-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postimage_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='preview',
        ),
    ]
